---

#
# Author: John McDonough (jomcdono@cisco.com)
#         Cisco Systems, Inc.
#
#############################
#  Playbook for ACI TENANTS #
#############################

- name: ACI Tenant Management
  hosts: aci
  connection: local
  gather_facts: no

  tasks:
  - name: Test that we have an ACI hostname, username, and password
    fail:
      msg: 'Please define the variables: aci_hostname, aci_username and aci_password.'
    when: aci_hostname is not defined or aci_username is not defined or aci_password is not defined
    vars:
      login_info: &login_info
        hostname: "{{ aci_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"

  - debug:
      msg: aci_state is {{ aci_state }}

  - name: Include Tenant vars
    include_vars:
      file: "{{ app_name }}.yml"

  - name: CONFIGURE TENANT
    aci_tenant:
      <<: *login_info
      tenant: "{{ tenant_name }}"
      description: "Tenant Created/Configured Using Ansible"
      state: "{{ aci_state }}"
      validate_certs: false
    when: aci_state == 'present'

  - name: TENANT TASKS
    include_tasks:
      file: tenant_tasks.yml
    when: aci_state == 'present'

  - name: DELETE TENANT
    aci_tenant:
      <<: *login_info
      tenant: "{{ tenant_name }}"
      state: "{{ aci_state }}"
      validate_certs: false
    when: aci_state == 'absent'
