---
# shared policies, use localhost so these tasks only run once
- hosts: intersight
  connection: local
  gather_facts: no
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
    boot_policy_name: vmedia-hdd2
    resource_state: present

  tasks:
  - name: Configure Boot Policy
    intersight_rest_api:
      <<: *api_info
      resource_path: /boot/PrecisionPolicies
      query_params:
        $filter: "Name eq '{{ boot_policy_name }}'"
      api_body: {
          "Name": "{{ boot_policy_name }}",
          "BootDevices": [
              {
                  "ObjectType": "boot.VirtualMedia",
                  "Enabled": true,
                  "Name": "remote-vmedia",
                  "Subtype": "cimc-mapped-dvd"
              },
              {
                  "ObjectType": "boot.LocalDisk",
                  "Enabled": true,
                  "Name": "boot-lun",
                  "Bootloader": null,
                  "Slot": "MRAID"
              }
          ],
          "ConfiguredBootMode": "Legacy",
          "EnforceUefiSecureBoot": false
      }
      state: "{{ resource_state }}"
